"""Gnani TTS - Python client for Gnani's multilingual Text-to-Speech API."""

from gnani.tts.client import (
    DEFAULT_MODEL,
    DEFAULT_SPEED,
    MAX_SPEED,
    MIN_SPEED,
    SUPPORTED_BITRATES,
    SUPPORTED_CONTAINERS,
    SUPPORTED_ENCODINGS,
    SUPPORTED_MODELS,
    SUPPORTED_TTS_LANGUAGES,
    SUPPORTED_VOICES,
    TIMBRE_MODELS,
    TIMBRE_V20_VOICES,
    TIMBRE_V25_VOICES,
    AudioConfig,
    GnaniTTSClient,
    GnaniTTSRealtimeClient,
    GnaniTTSStreamClient,
    SpeakerEmbedding,
    TTSAudioChunkEvent,
    TTSCompletedEvent,
    TTSStartEvent,
    TTSStreamEvent,
)
from gnani.tts.exceptions import (
    APIError,
    AuthenticationError,
    GnaniTTSError,
    StreamClosedError,
    StreamConnectionError,
    StreamError,
)

__all__ = [
    "DEFAULT_MODEL",
    "DEFAULT_SPEED",
    "MAX_SPEED",
    "MIN_SPEED",
    "SUPPORTED_BITRATES",
    "SUPPORTED_CONTAINERS",
    "SUPPORTED_ENCODINGS",
    "SUPPORTED_MODELS",
    "SUPPORTED_TTS_LANGUAGES",
    "SUPPORTED_VOICES",
    "TIMBRE_MODELS",
    "TIMBRE_V20_VOICES",
    "TIMBRE_V25_VOICES",
    "APIError",
    "AudioConfig",
    "AuthenticationError",
    "GnaniTTSClient",
    "GnaniTTSError",
    "GnaniTTSRealtimeClient",
    "GnaniTTSStreamClient",
    "SpeakerEmbedding",
    "StreamClosedError",
    "StreamConnectionError",
    "StreamError",
    "TTSAudioChunkEvent",
    "TTSCompletedEvent",
    "TTSStartEvent",
    "TTSStreamEvent",
]
