"""Gnani STT - Python client for Gnani's multilingual Speech-to-Text API."""

from gnani.stt.batch import (
    BatchFile,
    BatchJob,
    BatchResult,
    BatchSegment,
    GnaniSTTBatchClient,
)
from gnani.stt.batch_async import (
    AsyncBatchFile,
    AsyncBatchJob,
    AsyncBatchResult,
    AsyncGnaniSTTBatchClient,
)
from gnani.stt.client import (
    SAMPLE_RATE_8K,
    SAMPLE_RATE_16K,
    SAMPLE_RATE_44K,
    SAMPLE_RATE_48K,
    STREAM_CHUNK_BYTES,
    STREAM_CHUNK_SAMPLES,
    STREAM_SUPPORTED_LANGUAGES,
    STREAM_SUPPORTED_SAMPLE_RATES,
    SUPPORTED_LANGUAGES,
    GnaniSTTClient,
    GnaniSTTStreamClient,
    StreamConnectedEvent,
    StreamErrorEvent,
    StreamEvent,
    StreamProcessingEvent,
    StreamTranscriptEvent,
)
from gnani.stt.exceptions import (
    APIError,
    AuthenticationError,
    BatchJobFailedError,
    BatchTimeoutError,
    GnaniSTTError,
    InvalidAudioError,
    StreamClosedError,
    StreamConnectionError,
    StreamError,
)

__version__ = "0.7.9"
__all__ = [
    "SAMPLE_RATE_8K",
    "SAMPLE_RATE_16K",
    "SAMPLE_RATE_44K",
    "SAMPLE_RATE_48K",
    "STREAM_CHUNK_BYTES",
    "STREAM_CHUNK_SAMPLES",
    "STREAM_SUPPORTED_LANGUAGES",
    "STREAM_SUPPORTED_SAMPLE_RATES",
    "SUPPORTED_LANGUAGES",
    "APIError",
    "AsyncBatchFile",
    "AsyncBatchJob",
    "AsyncBatchResult",
    "AsyncGnaniSTTBatchClient",
    "AuthenticationError",
    "BatchFile",
    "BatchJob",
    "BatchJobFailedError",
    "BatchResult",
    "BatchSegment",
    "BatchTimeoutError",
    "GnaniSTTBatchClient",
    "GnaniSTTClient",
    "GnaniSTTError",
    "GnaniSTTStreamClient",
    "InvalidAudioError",
    "StreamClosedError",
    "StreamConnectedEvent",
    "StreamConnectionError",
    "StreamError",
    "StreamErrorEvent",
    "StreamEvent",
    "StreamProcessingEvent",
    "StreamTranscriptEvent",
]
